### ISSUE TITLE
Week 9 Script 1 is done and ready for grading - f2c.py

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#11]
I believe this one is correct.

**Comment by cethenmc** [comment]
Hi Nick.  These need work.  You do not have a main, not using the conditional __name__ and not returning anything out of convert_temp.  Please book me if you are having difficulty with the lesson, and I will be happy to help.  For now, I will enter a 3 of 8 in the gradebook, but you can resubmit and respond to this issue ticket when you have pushed corrections to GitHub.
