### ISSUE TITLE
Week 9 Script 2 - tempconversion.py

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#12]
I understand how to input the f2c.py into this script. i was also able to add a new temperature and it kicked back the new value. I also have the old value, and when i went to create a statement it comes up with "None" as the value instead of my new calculated value. I formatted it the same as the last video, so not sure what is wrong. thanks

Nick

**Comment by cethenmc** [comment]
Hi, Nick.  Please see my notes in the other week 9 script.  I recommend you take those hints to set f2c.py on the correct path, and then this one will make more sense.  Don't hesitate to book me through Blackboard > Instructor Contact.  If those times don't work than please email with other times of availability.

**Comment by cethenmc** [comment]
Hi, Nick.  The final project will be full of functions, so please take the time to review it and seek my help if you need it.  Thanks.  ~Chris

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208687005-881f8e61-b8f8-4cf4-b6f1-9c3ee1e51c74.png)

You should have corrected this lab to pick up some points on functions you missed on your final exam.
