### ISSUE TITLE
Week 11 - Arguments(ArgParse) This assignment is ready to be graded.

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#14]
I think this one went OK. Step 1 i believe is correct. Step 2 i think you just wanted us to setup  the script so it automatically printed the help command vs using -h to run the command. If i misinterpreted that it should be an easy fix to correct. I think this one is in a good spot.

Nick

**Comment by cethenmc** [comment]
Hi, Nick. If you try executing it with no additional arguments, it does pop up the help.  That is nice!  Also, I agree that you are in a perfect spot to fix the second part.  Here are some notes:

(1) We still want -h and --help to work.  This argument will work when you begin doing something with the arguments.
(2) None of the four arguments are printed.

Could you consider adding an else to your if statement in which you will print the four arguments described in Step 2 of the lab?

**Your grade is 6 of 8 for now.  Please resubmit soon with corrections for full credit.**

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208687005-881f8e61-b8f8-4cf4-b6f1-9c3ee1e51c74.png)
