### ISSUE TITLE
Week13 - Interacting with a Website is COMPLETE.

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#16]
I think this one went well. I feel like i completed all the pieces in each section. Thank you.

Nick Wanless

**Comment by cethenmc** [comment]
Nicely done!  8 out of 8.

We should change the question to print both the link label and the link.  Feel free to modify your last line if you desire:

print(f"{link.text}:  {link.get('href')}")

No need to resubmit.  You just might want to add it to your code when you review.
