### ISSUE TITLE
FINAL EXAM is Complete!!!

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#18]
This took me quite awhile, but I learned a lot in the processes. It was good review going back and re-watching videos. I think the Final looks good. Thank you.

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208699587-703de8b2-68f3-44df-adc5-5a53a94342dd.png)
