### ISSUE TITLE
Week 3 -Strings Assignment complete

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#3]
This assignment is ready to grade. Are we supposed to use the character codes at this point to add brackets or dashes for example?

**Comment by cethenmc** [comment]
Please fix punctuation in #3.

Use the correct fill character in #5.

For #12 and #13, download the word document for the assignment and get an accurate count of every place there is a space.  Don't use tabs.  As we learned they will render differently in different O.S.'s.  Hint:  #13 is the same as #12, just switch the $ with a space, and append the slicing on the two colors.  Please do count the spaces missing in #12 before goint to #13.

**Comment by nwanless-matc** [comment]
I have updated Week3. Thank you for the help. This is ready to grade now.

**Comment by cethenmc** [comment]
Nick - In Week 3, you have not reversed the word Red and Blue in #13. Would you like full credit or would you like a 7.43 out of 8 (92.875%)?  If full credit, I would allow you to fix and submit one more time.

**Comment by nwanless-matc** [comment]
I must be over looking something here. The red and blue in #13 look correct to me compared to the word document instructions. Maybe i am looking at the wrong thing. I will just take the 7.43.

**Comment by cethenmc** [comment]
Seriously, Nick, if they are showing up the correct way on your end, then perhaps you just never pushed them to GitHub after correcting.  Are you sure you just want the 7.43?

Here is what you show for 13:
[   Red    ] [  Green   ] [   Blue   ]
Here is what it should be:
[   deR    ] [  Green   ] [   eulB   ]

Also, I just noticed that on your last edit you skipped 14:
You show nothing for 14:
Here is what it should be:
First Color:[Red] Second Color:[Green] Third Color:[Blue]

**Comment by cethenmc** [comment]
Keeping the 7.43...closing the issue.
