### ISSUE TITLE
Week 5 - File Data Interactions is ready for Grading

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#5]
This week was a little more challenging for me than the previous couple of weeks. Please let me know if i misinterpreted any of the sections wrong. Thank you.

Nick wanless

**Comment by nwanless-matc** [comment]
I removed the text from the results of question 3. This should be ready to grade now.

**Comment by cethenmc** [comment]
Hi, Nick.  Good **start** on the clean-up, as it has given me enough to at least get a 5 of 8 in the grade book, but you can resubmit for full credit.  You struggle with 3, and if you would like to book to walk through, please book me through Instructor Contact in Blackboard.  Here are some tips if you want to fix it independently:

- don't use any read functions except for readline (and you will likely use this twice).
- use two different variables, one for the single line output of the readline(), and one for the cumulative collection of readline() outputs.
- calculate the length outside of the loop on the cumulative collection (now, I also won't dock if you calculate each line and keep adding it to a count like some have done, but that is more work for your script than necessary).
- I see the following with 3 and that needs to go away, as well.
000 [Length:010]
001 [Length:022]
002 [Length:048]...

**Comment by cethenmc** [comment]
Nick. Please let me know if you were going to go for the last three points on this lab or if I should close the issue and lock in the grade. ~Chris

**Comment by cethenmc** [comment]
Closing out the ticket and locking in the 5 of 8.
