### ISSUE TITLE
Week 6 Boolean logic (boolean.py) is complete and ready for grading.

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#6]
I hope i did this correctly. Were we just supposed to copy them into a script adding the bool() piece to see if they turned out true or false. That logically made since to me so we could go through the exercise prior and then verify our answers.

**Comment by cethenmc** [comment]
Nice work.  The first one is wrong.  7.6 of 8. I you would like to correct that one and resubmit, you could.  Please reply to this Issue if you repush the script to Git Hub or if you prefer taking the 7.6.  Thanks. ~Chris

**Comment by cethenmc** [comment]
Closing issue.  Locking in the 7.6 score.
