### ISSUE TITLE
Week 7 - Dictionaries.py assignment complete.

### ISSUE THREAD

**Issue by nwanless-matc** [madisoncollege-it-programs/python-scripting-nwanless-matc#8]
This assignment went pretty well. it is ready for grading. Thank you.

Nick Wanless

**Comment by cethenmc** [comment]
Nick.  The file is not executable at the line level.  Are you sure you ever tested it at the command line before submitting?  Please make it executable at the line level and then you will receive credit.  Until then, I am recording a 6 of 8.  Thanks. ~Chris

**Comment by cethenmc** [comment]
Please let me know if you'd like to make up the last two points, or if you would just like me to lock in the 6 out of 8 that is already in the grade book.  Thanks.  Chris

**Comment by cethenmc** [comment]
Closing ticket and locking in the 6 of 8.
